version: "3"
services:
    nginx:
        image: nginx:stable-alpine

        ports:
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #our default config will be added in nginx image we are bind mounting here syncing our local nginx configs
    node-app:
        build: .
        # ports: #no longere needed publish port for node now we are configuring nginx
        #     - "3000:3000"
        environment:
            - PORT=3000
        depends_on:
            - mongo
    # adding a database we can name it anythinlike mongo or mongodb
    mongo:
        image: mongo
        # restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=shuaib
        volumes:
            - mongo-db:/data/db

    redis:
        image: redis

volumes:
    mongo-db:
