version: "3"
services:
    node-app:
        build: .
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
        depends_on:
            - mongo
    # adding a database we can name it anythinlike mongo or mongodb
    mongo:
        image: mongo
        # restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=shuaib
        volumes:
            - mongo-db:/data/db

    redis:
        image: redis

volumes:
    mongo-db:
